name: nsvf.pytorch
description: Neural Sparse Voxel Fields (NSVF)
command: echo 'Hello world!'
setup_command: bash setup.sh
tags: ['NSVF']
priority: 1
parameters:
  whatsoever: 0
resources:
  num_gpus: 4
  group: 'p6:hw:ve'
  cluster: 'simcloud-mr2.apple.com'
  timeout: '14d'
  ports: ["TENSORBOARD_PORT"]
cluster_options:
  simcloud:
    smi: 'current-ubuntu18.04-cuda11.0'